server:
  port: 8090
  context-path: /reconiliation
  session:
    timeout: 3600

spring:
  datasource:
    url: jdbc:mysql://172.17.21.59:3306/eaccount
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 2
      max-idle: 10
      max-active: 20
      max-wait: 200
      test-on-borrow: true
  aop:
    auto: true

logging:
  level:
    root: INFO
    com.ucsmy.ucas: DEBUG
  file: logs/reconiliation.log

#是否启动quartz任务扫描器
quartz:
  scan: true


