server:
  port: 80
  context-path: /
  session:
    timeout: 3600

spring:
  datasource:
    url:
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 2
      max-idle: 10
      max-active: 20
      max-wait: 200
      test-on-borrow: true
  session:
    store-type: none

logging:
  level:
    root: INFO
    com.ucsmy.ucas: DEBUG


